dist: trusty
sudo: false
language: java

env:
  - ENVIRONMENT=
  - ENVIRONMENT=dev
  - ENVIRONMENT=prod

install:
  - true

before_script:
  - export ENV=$ENVIRONMENT && echo ENV:$ENV

after_script:
  - unzip -c build/libs/*.jar main.properties
